### ISSUE TITLE
General issues in README.md and test examples.

### ISSUE THREAD

**Issue by anubhavdas0907** [EBI-Metagenomics/kegg-pathways-completeness-tool#6]
Hello,

Thanks for building this useful tool.

I cloned the repo of this tool, and while running the tests, I found the following issues. Please look into it.

1. The file requirements.txt does not exist.

2. Details of all the required arguments not mentioned in README.md. And, warning while running the script "give_pathways.py".

```
python3 ./kegg_pathways_completeness/bin/give_pathways.py --help
./kegg_pathways_completeness/bin/give_pathways.py:134: SyntaxWarning: invalid escape sequence '\_'
  """
usage: give_pathways.py [-h] [-i INPUT_FILE] [-l INPUT_LIST] [-g GRAPHS] [-a PATHWAYS] [-n NAMES] [-c CLASSES] [-o OUTNAME] [-w] [-p]

Script generates Graphs for each contig

options:
  -h, --help            show this help message and exit
  -i INPUT_FILE, --input INPUT_FILE
                        Each line = pathway
  -l INPUT_LIST, --input-list INPUT_LIST
                        File with KOs comma separated
  -g GRAPHS, --graphs GRAPHS
                        graphs in pickle format
  -a PATHWAYS, --pathways PATHWAYS
                        Pathways list
  -n NAMES, --names NAMES
                        Pathway names
  -c CLASSES, --classes CLASSES
                        Pathway classes
  -o OUTNAME, --outname OUTNAME
                        first part of ouput name
  -w, --include-weights
                        add weights for each KO in output
  -p, --plot-pathways   Create images with pathways completeness

```
4. As per the example in README.md, the file test_kos.txt is not located in ./tests/test_data/test-input/test_kos.txt; The file is located in ./tests/fixtures/give_pathways/ .

5. The test run only works if it is run inside the folder repo folder. If ran from a different folder, the graph file could not be loaded due to issues with the default path.

Regards
Anubhav

**Comment by KateSakharova** [comment]
Hi @anubhavdas0907,
Thank you for using a tool and issue submittion. I've modified README. We have also pushed this tool to bioconda and pypi - that should simplify usage.
Best,
Kate
